# Generated by Django 4.0.4 on 2022-05-30 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='days_of_work',
        ),
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
        migrations.RemoveField(
            model_name='story',
            name='issue_key',
        ),
        migrations.RemoveField(
            model_name='story',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='story',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='story',
            name='summary',
        ),
        migrations.AddField(
            model_name='story',
            name='stories',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
