# Generated by Django 4.0.4 on 2022-05-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_story_days_of_work_remove_story_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
