# Generated by Django 4.0.4 on 2022-05-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
