# Generated by Django 4.0.4 on 2022-05-31 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
