# Generated by Django 4.0.4 on 2022-05-31 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_delete_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Form')),
                ('estimation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_key', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=30)),
                ('priority', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('days_of_work', models.FloatField()),
                ('entry', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.entry')),
            ],
        ),
    ]
